language: python
sudo: false
python:
  - "3.4"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  - pip
  - yarn
install:
  - yarn global add less coffeescript
  - pip install -r requirements-test.txt
  - yarn install --cwd _1327/static
script:
  - python manage.py lint
  - coverage run manage.py test
after_success:
  - coveralls
